name: CI for GitHub Pages site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Node-specific steps
    - name: Install node modules
      run: |
        npm install

    # Ruby-specific steps
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@ece82769428359c077b5a5eaff268902a303c101
      with:
        ruby-version: '3.0'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build and test with Rake
      run: bundle exec rake

    # Jekyll-specific steps
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod a+w /srv/jekyll/Gemfile.lock && chmod 777 /srv/jekyll && jekyll build --future"
